package main

const template_source=`package main

// This file is autogenerated by "go generate". Do not modify it.
// It has been generated from your {{.Plugin}}.yaml file. To update this file, update the yaml file.
// then do "go generate"
// If the template is incorrect, you need to fork github.hpe.com/christophe-larsonneur/go-forjj and update cmd/genflags/main.go

import (
  "gopkg.in/alecthomas/kingpin.v2"
  "github.hpe.com/christophe-larsonneur/goforjj"
  "os"
  "fmt"
)

type {{.Plugin}}App struct {
    goforjj.ForjjPluginApp
}

var cliApp {{.Plugin}}App

func (a *{{.Plugin}}App)init() {
  a.App = kingpin.New("{{.Plugin}}", "{{.Desc}}")
{{ if .Version }}\
  a.App.Version("{{ .Version }}")
{{ end }}\

  // true to create the Infra
  a.IsInfra = a.App.Flag("infra", "Used by upstream plugins to create initial repos.").Hidden().Bool()
  a.Flags = make(map[string]*string)
  a.Tasks = make(map[string]goforjj.PluginTask)
{{ range $Flagname, $Opts := .Cmds_m.common.Flags_m }}\
  a.Flags["{{ $Flagname }}"] = a.App.Flag("{{ $Flagname }}", "{{ $Opts.Opts_m.help }}")\
{{   if Test $Opts.Opts_m "required" "true" }}.Required(){{ end }}\
{{   if $Opts.Opts_m.default                }}.Default("{{$Opts.Opts_m.default}}"){{ end }}\
{{   if Test $Opts.Opts_m "hidden" "true"   }}.Hidden(){{ end }}.String()
{{ end }}

{{ range $cmd, $flags := (filter_cmds .Cmds_m) }}\
  a.Tasks["{{$cmd}}"] = goforjj.PluginTask {
    Flags: make(map[string]*string),
    Cmd  : a.App.Command("{{ $cmd }}", "{{ $flags.Help }}"),
  }
{{   range $Flagname, $Opts := $flags.Flags_m }}\
  a.Tasks["{{$cmd}}"].Flags["{{ $Flagname }}"] = a.Tasks["{{$cmd}}"].Cmd.Flag("{{ $Flagname }}", "{{ $Opts.Opts_m.help }}")\
{{     if Test $Opts.Opts_m "required" "true" }}.Required(){{ end }}\
{{     if $Opts.Opts_m.default                }}.Default("{{$Opts.Opts_m.default}}"){{ end }}\
{{     if Test $Opts.Opts_m "hidden" "true"   }}.Hidden(){{ end }}.String()
{{   end }}
{{ end }}\
}

func main() {
  cliApp.init()

  switch kingpin.MustParse(cliApp.App.Parse(os.Args[1:])) {
{{ range $cmd, $flags := (filter_cmds .Cmds_m) }}\
    case "{{$cmd}}":
       cliApp.{{$cmd}}()
{{ end }}\
  }
}

const YamlDesc="{{ escape .YamlDesc}}"

func ( *{{.Plugin}}App)check() {
  fmt.Printf("%s\n", YamlDesc)
}
`
